#spring:
#  application:
#    name: Slarud
#my:
#  custom:
#    property: '''Hello from application properties'''
#
#some:
#  second:
#    property: false
#
#custom:
#  login-url: test-login
#  credentials:
#    user: test-user
#    password: pass
